select * from customer;

--Q1. What is the total revenue
select sum(purchase_amount) as revenue from customer ;

--Q2. What is the total revenue generated by male vs. female customers?
select gender  , sum(purchase_amount) as revenue 
from customer 
group by gender; 

--Q3. What is the total revenue generated by different age_group customers?
select age_group , sum(purchase_amount) as revenue 
from customer
group by age_group;

--Q4. What is the total revenue generated by different age_group and gender customers?
select gender , age_group , sum(discount_applied) as revenue
from customer
group by gender , age_group;

--Q5. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q6. Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating :: numeric),2) 
from customer
group by item_purchased 
order by avg(review_rating)
limit 5 ;

--Q7. Compare the average Purchase Amounts between Standard and Express Shipping. 
select  shipping_type  , round(avg(purchase_amount),2) 
from customer
where shipping_type in ('Standard','Express') 
group by shipping_type;

--Q8. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status ,
count(customer_id) total_customers , 
round(avg(purchase_amount),2) as avg_spend, 
round(sum(purchase_amount),2)  as total_revenue 
from customer
group by subscription_status 
order by total_revenue , avg_spend desc ; 


--Q9. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id , previous_purchases ,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
    end as customer_segment
from customer
)
select customer_segment , count(*) as "Number Of Customers"
from customer_type
group by customer_segment;



--Q10. What are the top 3 most purchased products within each category? 
with item_counts as(
select category ,
item_purchased , 
count(customer_id) as total_orders ,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category , item_purchased 
)
select item_rank , category , item_purchased , total_orders
from item_counts 
where item_rank <= 3 ;



--Q11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status ,
count(customer_id) as  repeat_buyers 
from customer 
where previous_purchases > 5 
group by subscription_status ;



--Q12. What is the revenue contribution of each age group? 
select age_group ,
sum(purchase_amount) as total_revenue
from customer 
group by age_group 
order by total_revenue desc ;





